# Generated by Django 5.1.1 on 2024-09-09 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_hat'),
    ]

    operations = [
        migrations.AddField(
            model_name='hat',
            name='desc',
            field=models.TextField(default=10.0),
            preserve_default=False,
        ),
    ]
