# Generated by Django 5.1.1 on 2024-09-16 17:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_hat_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hat',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='moodentry',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
